# This is a basic workflow to help you get started with Actions

name: docker_dbt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: xemuliam/dbt:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: change directory
        run: cd $GITHUB_WORKSPACE

      - name: current directory
        run: pwd  

      - name: showing docs
        working-directory: ./dbt_github
        run: |
          dbt seed --profiles-dir /__w/Docker_DBT/Docker_DBT/dbt_github/.dbt
          dbt docs generate --profiles-dir /__w/Docker_DBT/Docker_DBT/dbt_github/.dbt
      
      - name: change directory
        run: cd $GITHUB_WORKSPACE

      - name: install git
        run: apt-get update && apt-get install -y git

      - name: Stage Changes
        run: |
          git add .
          git status
          git commit -m 'pushed the files to target'
          git push
          if [[ $(git log -1 --pretty=%B) == *"[skip ci]"* ]]; then
            echo "Skipping CI/CD."
            exit 0
          fi
